name = "jose"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[[kv_namespaces]]
binding = "JOSE"
id = "ac3eee4d513c4901accd137c94458fac"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "f067f384-2cb7-4fcb-9aba-2d2c240657e3"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/josebinsejo/inject/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/josebinsejo/inject/refs/heads/master/web/sub.html"
