name = "jose"
main = "build/worker/shim.mjs"
compatibility_date = "2025-06-11"
minify = true

[[kv_namespaces]]
binding = "JOSE"
id = "254f03ecc6dc40609f54871511b3a7d3"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "bd18d259-e301-42bd-86ee-601bcbe09b21"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/josebinjeso/inject/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/josebinsejo/inject/refs/heads/master/web/sub.html"
